apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: symfony-ns
  labels:
    app: mysql-app
    version: v1
spec:
  selector:
    matchLabels:
      app: mysql-app
      version: v1
  template:
    metadata:
      labels:
        app: mysql-app
        version: v1
    spec:
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: init-sql
          configMap:
            name: mysql-configmap

      containers:
        - name: mysql-container
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: USER_QUERIES
              valueFrom:
                secretKeyRef:
                  name: user-queries-secret
                  key: USER_QUERIES
            - name: MYSQL_DATABASE
              value: app
          # livenessProbe:
          #   exec:
          #     command:
          #     - bash
          #     - -c
          #     - mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD}
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          # readinessProbe:
          #   exec:
          #     command:
          #     - bash
          #     - -c
          #     - mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1"
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 3
          #   failureThreshold: 2
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/01-schema.sql
              subPath: 01-schema.sql
          command: ["sh", "-c"]
          args:
            - |
              # Esto se hace para mantener un equilibrio entre seguridad y reproducibilidad del proyecto a terceros, pero lo ideal es crear los usuarios a través de migración o jobs externos
              echo "$USER_QUERIES" > /docker-entrypoint-initdb.d/02-users.sql
              exec docker-entrypoint.sh mysqld
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
