# k8s/overlays/aws/observability/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-ns # Funciona aunque aún no exista el namespace

resources:
  - ../../../base/observability
  - ingresses/ingress-grafana.yaml
