server {
    listen 80;
    server_name _;

    root /var/www/html/public;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        # Con docker compose, el host del servicio PHP es el nombre del servicio definido en docker-compose.yml: symfony-php-service:9000
        # Con K8s, el host del servicio PHP está en el mismo pod: localhost:9000
        fastcgi_pass ${FASTCGI_HOST}:${FASTCGI_PORT};
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
