index:
    path: /
    controller: App\Controller\DefaultController::index

producto_detalle:
    path: /producto/{idProducto}
    controller: App\Controller\ProductosController::detalle

error_test:
    path: /error-test
    controller: App\Controller\ErrorController::error

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
