apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: symfony-ns
  labels:
    app: mysql-app
    version: v1
spec:
  selector:
    app: mysql-app
  ports:
    - name: mysql
      port: 3306
