apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring-ns
  labels:
    app: node-exporter-app
    version: v1
spec:
  selector:
    app: node-exporter-app
  ports:
    - port: 9100
      targetPort: 9100
      name: metrics
  type: ClusterIP
