apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: monitoring-ns
  labels:
    app: opentelemetry-app
    version: v1
spec:
  selector:
    app: opentelemetry-app
  ports:
    - port: 4317
      targetPort: 4317
      name: grpc
    - port: 4318
      targetPort: 4318
      name: http
    - port: 9464
      targetPort: 9464
      name: prometheus
  type: ClusterIP
