apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring-ns
  labels:
    app: cadvisor-app
    version: v1
spec:
  selector:
    app: cadvisor-app
  ports:
    - port: 8080
      targetPort: 8080
      name: metrics
  type: ClusterIP
