{
 "title": "Observabilidad app",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ítems carrito por usuario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "items_carrito_usuarios_total", "legendFormat": "{{usuario}}" }
   ]
  },
  {
   "title": "Usuarios vs Anónimos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(solicitud_productos_usuarios_total{usuario=\"anónimo\"})",
     "legendFormat": "Usuarios anónimos"
    },
    {
     "expr": "sum(solicitud_productos_usuarios_total) - sum(solicitud_productos_usuarios_total{usuario=\"anónimo\"})",
     "legendFormat": "Usuarios registrados"
    }
   ]
  },
  {
   "title": "Solicitud de productos por usuario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "solicitud_productos_usuarios_total",
     "legendFormat": "{{producto_nombre}} de {{usuario}}"
    },
    {
     "expr": "sum(solicitud_productos_usuarios_total)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Solicitud de productos (cantidad)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "solicitud_productos_total", "legendFormat": "{{producto_nombre}}" },
    { "expr": "sum(solicitud_productos_total)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Solicitud de productos (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(solicitud_productos_total[1m]))",
     "legendFormat": "Solicitud de productos"
    }
   ]
  }
 ]
}