{
 "title": "Observabilidad nodo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "🖥️ Uso de CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🖥️ Uso de memoria (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "Memoria"
    }
   ]
  },
  {
   "title": "🔀 Tráfico de red",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "Bytes recibidos"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "Bytes enviados"
    }
   ]
  },
  {
   "title": "💾 Espacio en disco",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(node_filesystem_avail_bytes{ }/1000000000)",
     "legendFormat": "Media"
    }
   ]
  }
 ]
}