apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: symfony-app-externalsecret
  namespace: symfony-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: symfony-secretstore
    kind: SecretStore
  target:
    name: symfony-app-secret
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: symfony-app-secret
        property: APP_SECRET
