apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-externalsecret
  namespace: symfony-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: symfony-secretstore
    kind: SecretStore
  target:
    name: mysql-secret
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: symfony-mysql-root-password
        property: MYSQL_ROOT_PASSWORD
