apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: symfony-database-externalsecret
  namespace: symfony-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: symfony-secretstore
    kind: SecretStore
  target:
    name: symfony-database-secret
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: symfony-database-url
        property: DATABASE_URL
