apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-deployment
  namespace: symfony-ns
spec:
  replicas: 2 # Revisar sticky sessions en el ingres y en AWS ALB
  selector:
    matchLabels:
      app: symfony-app
  template:
    metadata:
      labels:
        app: symfony-app
    spec:
      volumes:
        - name: app-logs
          persistentVolumeClaim:
            claimName: symfony-pvc

      containers:
        - name: php-nginx-container
          image: mysymfony/php-nginx:4.1
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: symfony-secret
                  key: DATABASE_URL
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: app-logs
              mountPath: /var/www/html/var/log
          ports:
            - containerPort: 80
