apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-queries-externalsecret
  namespace: symfony-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: symfony-secretstore
    kind: SecretStore
  target:
    name: user-queries-secret
  data:
    - secretKey: USER_QUERIES
      remoteRef:
        key: symfony-user-queries
        property: USER_QUERIES
