# k8s/deployments/loki.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  namespace: monitoring-ns
  labels:
    app: loki-app
    version: v1
spec:
  selector:
    matchLabels:
      app: loki-app
      version: v1
  template:
    metadata:
      labels:
        app: loki-app
        version: v1
    spec:
      volumes:
        - name: config
          configMap:
            name: loki-config
      
      containers:
        - name: loki
          image: grafana/loki:3.5.5
          args:
            - '-config.file=/etc/loki/local-config.yaml'
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: config
              mountPath: /etc/loki
          ports:
            - containerPort: 3100
              name: http
