apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: monitoring-ns
  labels:
    app: grafana-app
    version: v1
spec:
  selector:
    matchLabels:
      app: grafana-app
      version: v1
  template:
    metadata:
      labels:
        app: grafana-app
        version: v1
    spec:
      volumes:
        - name: datasources-config
          configMap:
            name: datasources-config
        - name: dashboards-config
          configMap:
            name: dashboards-config
        - name: alerting-config
          configMap:
            name: alerting-config
        - name: dashboards
          configMap:
            name: dashboards
      
      containers:
        - name: grafana
          image: grafana/grafana:12.1.1
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: "traceqlEditor"
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: datasources-config
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
            - name: alerting-config
              mountPath: /etc/grafana/provisioning/alerting
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
          ports:
            - containerPort: 3000
              name: http
