# k8s/overlays/aws/application/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: symfony-ns # Funciona aunque aún no exista el namespace

resources:
  - ../../../base/application
  - secretstores/secretstore-symfony.yaml
  - externalsecrets/externalsecret-app-symfony.yaml
  - externalsecrets/externalsecret-database-symfony.yaml
  - externalsecrets/externalsecret-mysql.yaml
  - externalsecrets/externalsecret-user-queries.yaml
  - volumes/pvc-mysql.yaml
  - volumes/pvc-symfony.yaml
  - deployments/deployment-symfony.yaml
  - ingresses/ingress-symfony.yaml
