apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: symfony-ns
spec:
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      volumes:
        - name: mysql-data
          # Cambiar esto a PersistentVolumeClaim en producción
          emptyDir: {}

      containers:
        - name: mysql-container
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: app
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
