apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: symfony-ns
data:
  init.sql: |
    -- --------------------------------------------------------
    -- Host:                         192.168.100.2
    -- Server version:               8.0.45 - MySQL Community Server - GPL
    -- Server OS:                    Linux
    -- HeidiSQL Version:             12.15.0.7171
    -- --------------------------------------------------------

    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET NAMES utf8 */;
    /*!50503 SET NAMES utf8mb4 */;
    /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
    /*!40103 SET TIME_ZONE='+00:00' */;
    /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
    /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
    /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


    -- Dumping database structure for app
    CREATE DATABASE IF NOT EXISTS `app` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
    USE `app`;

    -- Dumping structure for table app.doctrine_migration_versions
    CREATE TABLE IF NOT EXISTS `doctrine_migration_versions` (
      `version` varchar(191) COLLATE utf8mb3_unicode_ci NOT NULL,
      `executed_at` datetime DEFAULT NULL,
      `execution_time` int DEFAULT NULL,
      PRIMARY KEY (`version`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

    -- Dumping data for table app.doctrine_migration_versions: ~0 rows (approximately)
    DELETE FROM `doctrine_migration_versions`;
    INSERT INTO `doctrine_migration_versions` (`version`, `executed_at`, `execution_time`) VALUES
      ('DoctrineMigrations\\Version20260217100651', '2026-02-17 10:08:21', 163),
      ('DoctrineMigrations\\Version20260219121845', '2026-02-19 12:19:50', 63);

    -- Dumping structure for table app.messenger_messages
    CREATE TABLE IF NOT EXISTS `messenger_messages` (
      `id` bigint NOT NULL AUTO_INCREMENT,
      `body` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
      `headers` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
      `queue_name` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
      `created_at` datetime NOT NULL,
      `available_at` datetime NOT NULL,
      `delivered_at` datetime DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `IDX_75EA56E0FB7336F0` (`queue_name`),
      KEY `IDX_75EA56E0E3BD61CE` (`available_at`),
      KEY `IDX_75EA56E016BA31DB` (`delivered_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    -- Dumping data for table app.messenger_messages: ~0 rows (approximately)
    DELETE FROM `messenger_messages`;

    -- Dumping structure for table app.producto
    CREATE TABLE IF NOT EXISTS `producto` (
      `id` int NOT NULL AUTO_INCREMENT,
      `nombre` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
      `descripcion` longtext COLLATE utf8mb4_unicode_ci,
      `precio` decimal(10,2) DEFAULT NULL,
      `imagen` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
      `created_at` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    -- Dumping data for table app.producto: ~6 rows (approximately)
    DELETE FROM `producto`;
    INSERT INTO `producto` (`id`, `nombre`, `descripcion`, `precio`, `imagen`, `created_at`) VALUES
      (1, 'Zapatillas Running', 'Zapatillas ideales para running con amortiguación de alta calidad.', 89.99, 'sneakers.jpg', '2026-02-19 00:00:00'),
      (2, 'Camiseta Deportiva', 'Camiseta transpirable para actividades deportivas.', 29.99, 't-shirt.jpg', '2026-02-18 00:00:00'),
      (3, 'Riñonera', 'Riñonera práctica con múltiples compartimentos.', 19.99, 'fanny-pack.jpg', '2026-02-17 00:00:00'),
      (4, 'Calcetines Técnicos (Pack 3)', 'Calcetines acolchados con tecnología antiolor y refuerzos en zonas de impacto.', 19.99, 'socks-pack.jpg', '2026-02-16 00:00:00'),
      (5, 'Gorra Running UV', 'Gorra transpirable con protección UV y banda antisuor. Ajuste regulable.', 15.99, 'cap-running.jpg', '2026-02-15 00:00:00'),
      (6, 'Mochila Hidratación', 'Mochila ligera con bolsa de agua incluida. Ideal para trails y largas distancias.', 45.99, 'backpack-water.jpg', '2026-02-14 00:00:00');

    -- Dumping structure for table app.user
    CREATE TABLE IF NOT EXISTS `user` (
      `id` int NOT NULL AUTO_INCREMENT,
      `email` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
      `roles` json NOT NULL,
      `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
      `first_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `UNIQ_8D93D649E7927C74` (`email`)
    ) ENGINE=InnoDB AUTO_INCREMENT=118 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    -- Dumping data for table app.user: ~11 rows (approximately)
    DELETE FROM `user`;
    INSERT INTO `user` (`id`, `email`, `roles`, `password`, `first_name`) VALUES
      (107, 'abraca_admin@example.com', '[]', '$2y$13$1RkjZnqADmHTpwVdw03PUe0CqxeicZ6KlPzb70kSf8I.SmFy1/fx2', 'Fermin'),
      (108, 'ischroeder@kling.biz', '[]', '$2y$13$NQTzmmxEr7Arz8rbrPmCz.ioEC2iaiIWONPKkpBnQ6FZ0X.8Cjhm6', 'Humberto'),
      (109, 'ivy53@windler.com', '[]', '$2y$13$8pMCnpQJ1mKhEl1p0.tG1.L7iPjI1BRyjOTdr8PPPsBhQH5v.3GOq', 'Lily'),
      (110, 'lhermiston@hotmail.com', '[]', '$2y$13$EnhThvLx.wdY75757dLguufUOtOqdCmgTSvyMcP3bE60UyuTQkoVO', 'Tia'),
      (111, 'mekhi.jenkins@hotmail.com', '[]', '$2y$13$iZEpNcJ4UmPC5n3H.n539OKzsFp0o31zwFcUeRO6dC0yLWd3kgBy.', 'Marcella'),
      (112, 'triston86@marvin.net', '[]', '$2y$13$822oQOGxoLm9.iIz5B.2ouINjQ9PMR/GgSwYVNesjmJUGOC7RHr0G', 'Cora'),
      (113, 'molly59@hill.info', '[]', '$2y$13$paW7goIIafn9nhTn56utiuIt8sLmj9EsMol.KM2QHzx8m43ZZh/Ki', 'Louie'),
      (114, 'nienow.sarah@casper.org', '[]', '$2y$13$39W4VNtefZ/smKKjLHGn/ul1e3lDFzk2Xux0okE6CzMR5Ben.sb.y', 'Kelli'),
      (115, 'craig.berge@schaefer.biz', '[]', '$2y$13$kggeZ0EjMLmF7X39I4eUmexJGtaJzOZWeScjxPkund7xRSIcSTX.G', 'Leta'),
      (116, 'towne.muhammad@beier.org', '[]', '$2y$13$FhzUp4u2sUdV4cmBRokFo.8cmvdp5ojcEbPLppZgYBDYIkSmzEQqS', 'Rosemary'),
      (117, 'nickolas25@gmail.com', '[]', '$2y$13$.300UxcH0Zv1BAAvrxfBLu1xrP4DMeKJIYWFDk4yngEYB0sQhQjAq', 'Maya');

    /*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
    /*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
    /*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
