apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: symfony-pvc
  namespace: symfony-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi # Uso inicial de 90M, ir ajustando conforme vayas terminando
  # Sin storageClassName → usa el default
