apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: symfony-secretstore
  namespace: symfony-ns
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      # Si se indica explícitamente, dará error porque no se puede autenticar a una SA de otro namespace y habría que crear una SA en este namespace para el mismo propósito
      # Teniendo la que crea Helm chart (helm-eso.tf), no hace falta indicarlo y las peticiones de los secrets se gestionarán de forma automática
      # auth:
      #   jwt:
      #     serviceAccountRef:
      #       name: external-secrets
      #       namespace: external-secrets
